---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-fake-exporter
spec:
  replicas: 1
  metadata:
    annotations:
      # Automatic prometheus scraping
      prometheus.io/port: '9100'
      prometheus.io/scrape: 'true'
      scope: cluster
    labels:
      k8s-app: node-exporter
  spec:
    automountServiceAccountToken: false
    containers:
    - image: docker-registry.default.svc:5000/openshift-monitoring/prometheus-node-exporter:fake
      name: prometheus-fake-exporter
      ports:
      - containerPort: 9100
      env:
      - name: LABEL_NAME
        value: deployment
      - name: LABEL_VALUE
        value: prometheus-fake-exporter
      - name: VALUE_HTTP_ENDPOINT
        value: https://gist.githubusercontent.com/3h4x/38ba057db9cbb80c7bf8ad768a90d086/raw/value
      - name: POD_NAMESPACE
        valueFrom:	
          fieldRef:	
            fieldPath: metadata.namespace
