apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: federatorai-emulator-1
  name: federatorai-emulator-1
  namespace: openshift-monitoring
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: federatorai-emulator-1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: federatorai-emulator-1
    spec:
      containers:
        - env:
            - name: LABEL_NAME
              value: deployment
            - name: LABEL_VALUE
              value: federatorai-emulator
            - name: VALUE_HTTP_ENDPOINT
              value: >-
                https://gist.githubusercontent.com/3h4x/38ba057db9cbb80c7bf8ad768a90d086/raw/value
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: FAKE_SERVER_PORT
              value: '9300'
          image: >-
            docker-registry.default.svc:5000/openshift-monitoring/federatorai-emulator:latest
          imagePullPolicy: IfNotPresent
          name: federatorai-emulator
          ports:
            - containerPort: 9300
              hostPort: 9300
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /host/proc
              name: proc
            - mountPath: /host/sys
              name: sys
            - mountPath: /host/root
              mountPropagation: HostToContainer
              name: root
              readOnly: true
            - name: federatorai-emulator-config-1
              mountPath: /etc/emulator/emulator.toml
              subPath: emulator.toml
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: node-exporter
      serviceAccountName: node-exporter
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      volumes:
        - hostPath:
            path: /proc
            type: ''
          name: proc
        - hostPath:
            path: /sys
            type: ''
          name: sys
        - hostPath:
            path: /
            type: ''
          name: root
        - name: node-exporter-tls
          secret:
            defaultMode: 420
            secretName: node-exporter-tls
        - name: federatorai-emulator-config-1
          configMap:
            name: federatorai-emulator-config-1
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
